config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :events

  get "/items/claims", to: "items#claims"
  post "/items/claim/:id", to: "items#claim", as: "claim"
  post "/items/release/:id", to: "items#release", as: "release"
  resources :items

  resources :categories
  resource :registrations

  resources :subscriptions
  post "/subscribe", to: "subscriptions#subscribe"
  post "/unsubscribe", to: "subscriptions#unsubscribe"

  get "/home", to: "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]
  before_action :protected_action, only: %i[ create update destroy ]
  before_action :protected_view, only: %i[ index new edit ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to subscriptions_path, status: :see_other, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def subscribe
    if Subscription.exists?(user: Current.user)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("subscribe-cta", partial: "subscribe_cta") }
      end
    else
      s = Subscription.new
      s.user = Current.user
      s.save!

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("subscribe-cta", partial: "subscribe_cta") }
      end
    end
  end

  def unsubscribe
    s = Subscription.find_by(user: Current.user)
    if s.nil?
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("subscribe-cta", partial: "subscribe_cta") }
      end
    else
      s.destroy!

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("subscribe-cta", partial: "subscribe_cta") }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.expect(subscription: [ :user_id, :meta ])
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_field :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscribe_cta.html.erb
<turbo-frame id="subscribe-cta">
  <% if Subscription.exists?(user: Current.user) %>
    <%= button_to [:unsubscribe], 
              class: "outline secondary flex-between", 
              style: "gap: 6px" do %>
      <%= icon "check" %>
      Subscribed
    <% end %>
  <% else %>
    <%= button_to [:subscribe], 
              class: "flex-between", 
              style: "gap: 6px" do %>
      <%= icon "plus" %>
      Subscribe
    <% end %>
  <% end %>
</turbo-frame>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>User:</strong>
    <%= subscription.user_id %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= subscription.meta %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<% content_for :title, "Editing subscription" %>

<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Subscriptions" %>

<h1>Subscriptions</h1>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
  <% end %>
</div>

<%= link_to "New subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<% content_for :title, "New subscription" %>

<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>

app/views/subscriptions/subscribe_cta.erb
<turbo-frame id="subscribe-cta">
  <%= render partial: "subscribe_cta" %>
</turbo-frame>