config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :events

  get "/items/claims", to: "items#claims"
  post "/items/claim/:id", to: "items#claim", as: "claim"
  post "/items/release/:id", to: "items#release", as: "release"
  resources :items

  resources :categories
  resource :registrations

  resources :subscriptions
  post "/subscribe", to: "subscriptions#subscribe"
  post "/unsubscribe", to: "subscriptions#unsubscribe"

  get "/home", to: "home#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Moving Jordans Casa" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Cloudflare's improvement on ReCaptcha %>
    <%= cloudflare_turnstile_script_tag %>
  </head>

  <body>
    <% if authenticated? %>
      <dialog id="navigation-menu" class="navigation-slideout-container">
        <aside class="navigation-slideout">
          <nav>
            <button class="icon" style="display: flex; margin-left: auto"
                  data-controller="popup" data-action="click->popup#close">
              <%= icon "caret-double-left" %>
            </button>
            <ul class="mt">
              <li><%= link_to "Home", root_path, class: "secondary" %></li>
              <li><%= link_to "Events", events_path, class: "secondary" %></li>
              <li><%= link_to "Item Giveaways", items_path, class: "secondary" %></li>
              <li><%= link_to "Newsletter", root_path, class: "secondary" %></li>
            </ul>
          </nav>
          <div class="flex-column">
            <p class="tight">Hi there, <span class="username">@<%= Current.user.display_name %></span></p>
            <div>
              <%= link_to "Edit your profile", edit_registrations_path %>
            </div>
            <%= button_to "Log out", session_path, method: :delete if authenticated? %>
          </div>
        </aside>
      </dialog>
    <% end %>
    <header class="flex-between container">
      <div class="flex-left" style="gap: 16px">
        <% if authenticated? %>
          <button class="icon" data-controller="popup" data-action="click->popup#openNavigation">
            <%= icon "caret-double-right" %>
          </button>
        <% end %>
        <h1 class="site-title" style="margin-bottom: 10px"><%= link_to "moving.jordans.casa", root_path %></h1>
      </div>
    </header>
    <main class="container">
      <%= yield %>
    </main>
    <% if authenticated? %>
      <footer class="grid container">
        <small style="text-align: center; color: var(--pico-color-grey-250)">
          <div style="font-style: italic;">Made with <%= icon "heart", variant: "fill", class: "inline pico-color-pumpkin-350" %> by Aaron</div>
          <div class="mt mb"><a href="https://github.com/aaronjordan/moving-jordans-casa" target="_blank" class="secondary">Check it out on GitHub!</a></div>
        </small>
      </footer>
    <% end %>
  </body>
</html>